---
- hosts: all

  tasks:
    - name: Testing connection
      win_ping:

# Restart snmp
    - name: Ensuring SNMP is started
      win_service:
        name: snmptrap
        state: started

    - name: Installing IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

    - name: Deploying website
      win_copy: src=/etc/ansible/html/ dest=C:/inetpub/wwwroot
      notify:

      - iis reset

    - name: restarting the appool
      win_iis_webapppool:
         name: "DefaultAppPool"
         state: restarted

  handlers:

    - name: iis reset
      win_service:
        name: w3svc
        state: restarted


